-- INSERT INTO customer (name, email, gender) VALUES ('HOMEM ARANHA', 'aranha@vingadores.com', 'M');
-- INSERT INTO customer (name, email, gender) VALUES ('THOR', 'thor@vingadores.com', 'M');
-- INSERT INTO customer (name, email, gender) VALUES ('VIUVA NEGRA', 'viuva@vingadores.com', 'F');
-- INSERT INTO customer (name, email, gender) VALUES ('NAMOR', 'namor@vingadores.com', 'M');
-- INSERT INTO customer (name, email, gender) VALUES ('GAMORA', 'gamora@vingadores.com', 'F');